version: 2
jobs:

  hugo-publish:
    machine: true
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.tar.gz | tar xzf - hugo
            chmod +x hugo
            ./hugo --destination=.deploy/
            git config --global user.email "username.taken@gmail.com"
            git config --global user.name "Hugo Publisher"
            git checkout gh-pages
            rm -rf ./*
            mv .deploy/* .
            echo "k8s.camp" > CNAME
            git add .
            git commit --message="publish k8s.camp" --signoff
            git push "$CIRCLE_REPOSITORY_URL" gh-pages

workflows:
  version: 2
  release:
    jobs:
      - hugo-publish:
          filters:
            tags:
              ignore: /.*/
            branches:
              only: master