name: Integration Tests
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches: [master]
jobs:
  build:
    name: spell-check
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: ./.github/actions/spell-check
